-- Target Database : MYSQL

-- Tables
CREATE TABLE BALISE (
	ID decimal(19, 0) NOT NULL COMMENT 'Technical ID',
	NOM varchar(20) DEFAULT 'Opérateur' NOT NULL COMMENT 'Nom'
) ENGINE = InnoDB;
ALTER TABLE BALISE COMMENT='Balise';
ALTER TABLE BALISE ADD CONSTRAINT BALISE_BALISE_PK PRIMARY KEY (ID);
CREATE TABLE LOCALISATION (
	ID decimal(19, 0) NOT NULL COMMENT 'Technical ID',
	COORD_X decimal(7, 5) NULL COMMENT 'Coordonnée x',
	COORD_Y decimal(7, 5) NULL COMMENT 'Coordonnée y',
	HEURE timestamp NULL COMMENT 'Heure',
	STATUT BOOL DEFAULT 1 NOT NULL COMMENT 'Statut',
	BALISE_ID decimal(19, 0) NOT NULL COMMENT 'Technical ID'
) ENGINE = InnoDB;
ALTER TABLE LOCALISATION COMMENT='Localisation';
ALTER TABLE LOCALISATION ADD CONSTRAINT LOCALISATION_LOCALISATION_PK PRIMARY KEY (ID);
CREATE INDEX LOCALISATION_BALISE_FK ON LOCALISATION (BALISE_ID ASC) ;

-- Foreign key constraints 
ALTER TABLE LOCALISATION ADD CONSTRAINT LOCALISATION_R_BALISE FOREIGN KEY (BALISE_ID) REFERENCES BALISE (ID) ON DELETE CASCADE ON UPDATE CASCADE;

